baseURL = 'jeffkwang.github.io'
languageCode = 'en-us'
title = 'Jeff Wang : Writings'
theme = "m10c"

[params]
    author = "Jeff Wang"
    description = "All views expressed are my own. All views are meant to be of my personal, subjective experiences."

    [[params.social]]
        icon = "linkedin"
        name = "LinkedIn"
        url = ""


