baseURL = 'https://jeffkwang.github.io/wall-of-writing/'
languageCode = 'en-us'
title = "Jeff's Wall of Writing"
theme = "paper"

[params]
    color = "wheat"
    
    linkedin = "https://www.linkedin.com/in/jeff-wang-00/"

    avatar = 'https://avatars.githubusercontent.com/u/55214987?v=4'
    name = 'Jeff Wang'


